name: Daily schedule

on:
  schedule:
    - cron: "0 5 * * *"     # 05:00 UTC = 08:00 по Москве
  workflow_dispatch:         # кнопка для ручного запуска

jobs:
  send-schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
